version: '3'
services:
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/shop-app/backend
    environment:
      DB_HOST: db
      DB_NAME: appdb
      DB_USERNAME: user
      DB_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/shop-app/frontend
      - /shop-app/frontend/node_modules
    command: yarn dev
    depends_on:
      - backend
